//
//  CountryManager.swift
//  CountryApp
//
//  Created by Panah Suleymanli on 13.04.24.
//

import Foundation

class CountryManager {
    func manage() ->[Countries] {
        return [Countries(name: "Azerbaijan", flag: "azerbaijan-flag", cities: [Cities(name: "Baku", logo: "baku", info: "Baku, far more than just the capital of Azerbaijan, sits as the historical, cultural and business center of this West Asian country. Aptly nicknamed the City of Winds, Baku’s location on the western shore of the Caspian Sea subjects it to strong winds throughout the year while also gracing the city with gorgeous seaside views. With a population of over 2 million people, Baku is the largest city on the Caspian Sea and in the entire Caucasus region."),
             Cities(name: "Seki", logo: "seki", info: "Shaki (Azerbaijani: Şəki) is a city in northwestern Azerbaijan, surrounded by the district of the same name. It is located in the southern part of the Greater Caucasus mountain range, 240 km (150 mi) from Baku. As of 2020, it has a population of 68,400.[2] The center of the city and the Palace of Shaki Khans were inscribed in the UNESCO World Heritage List in 2019 because of their unique architecture and history as an important trading center along the Silk Road.            According to the Azerbaijani historians, the name of the town goes back to the ethnonym of the Sakas, who reached the territory of modern-day Azerbaijan in the 7th century B.C. and populated it for several centuries.[4] In the medieval sources, the name of the town is found in various forms such as Sheke, Sheki, Shaka, Shakki, Shakne, Shaken, Shakkan, Shekin.") ]),
                Countries(name: "Turkey", flag: "turkey", cities: [Cities(name: "Istanbul", logo: "istanbul", info: "Istanbul is the largest city in Turkey, constituting the country's economic, cultural, and historical heart. Its commercial and historical centre lies in the European part of Eurasia, while about a third of its population lives in the Asian part. With a population of 14.1 million, the city forms the largest urban agglomeration in Europe as well as the largest in the Middle East, and the sixth-largest city proper in the world. Istanbul's vast area of 5,343 square kilometres is coterminous with Istanbul Province, of which the city is the administrative capital. Istanbul is a transcontinental city, straddling the Bosphorus strait in northwestern Turkey between the Sea of Marmara and the Black Sea.Founded on the Sarayburnu promontory around 660 BC as Byzantium, the city now known as Istanbul developed to become one of the most significant cities in history. For nearly sixteen centuries following its reestablishment as Constantinople in 330 AD, it served as the capital of four empires: the Roman Empire (330–395), the Byzantine Empire (395-1204 and 1261-1453), the Latin Empire (1204-1261), and the Ottoman Empire (1453-1922). It was instrumental in the advancement of Christianity during Roman and Byzantine times, before the Ottomans conquered the city in 1453 and transformed it into an Islamic stronghold and the seat of the last caliphate.Istanbul's strategic position along the historic Silk Road, rail networks to Europe and the Middle East, and the only sea route between the Black Sea and the Mediterranean have helped foster an eclectic populace, although less so since the establishment of the Republic in 1923. Overlooked for the new capital during the interwar period, the city has since regained much of its prominence. The population of the city has increased tenfold since the 1950s, as migrants from across Anatolia have flocked to the metropolis and city limits have expanded to accommodate them. Arts festivals were established at the end of the 20th century, while infrastructure improvements have produced a complex transportation network."),
                     Cities(name: "Izmir", logo: "izmir", info: "Izmir is a metropolitan city in the western extremity of Turkey and the third most populous city in Turkey, after Istanbul and Izmir.Once the ancient city of Smyrna, İzmir is now a modern, developed, and busy commercial center, set around a huge bay and surrounded by mountains. The broad boulevards, glass-fronted buildings and modern shopping centers are dotted with traditional red-tiled roofs, the 18th century market, and old mosques and churches, although the city has an atmosphere more of Mediterranean Europe than traditional Turkey.İzmir owes its position as an economically and socially dynamic city to its location, climate and the fact that it has been a home to many different cultures and religions. Persians, Ancient Greeks, Assyrians, Romans, Byzantines and Ottomans are just a few of the dozens of different civilizations that the city has hosted throughout its long history.Lying on an advantageous location at the head of a gulf running down in a deep indentation, midway on the western Anatolian coast, it has been one of the principal mercantile cities of the Mediterranean Sea for much of its history. Izmir hosted the Mediterranean Games in 1971 and the World University Games in 2005.In classical antiquity the city was known as Smyrna. Izmir has almost 4,000 years of recorded urban history and possibly even longer as an advanced human settlement. Set in an advantageous location at the head of a gulf in a deep indentation midway along the western Anatolian coast, the city has been one of the principal mercantile cities of the Mediterranean Sea for much of its history. Its port is Turkey's primary port for exports in terms of the freight handled and its free zone, a Turkish-U.S. joint-venture established in 1990, is the leader among the twenty in Turkey.") ])]
                
    }
}
